services:
  prometheus:
    image: docker.io/prom/prometheus:v3.4.0
    networks:
      - pg-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus

  grafana:
    image: docker.io/grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    networks:
      - pg-network
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards

  renderer:
    image: docker.io/grafana/grafana-image-renderer:3.12.6
    networks:
      - pg-network

  pgload:
    image: pgload:0.1.0
    build:
      context: ../pgload
    networks:
      - pg-network
    environment:
      - PGLOAD_MODE=replication
      - PGLOAD_NODES_DSN=
        postgresql://dba:sql@haproxy:5432/ecommerce
        postgresql://dba:sql@haproxy:5433/ecommerce
      - PGLOAD_HEALTH_CHECK_TIMEOUT=240
      - PGLOAD_WRITE_DSN=postgresql://dba:sql@haproxy:5432/ecommerce
      - PGLOAD_READ_DSN=postgresql://dba:sql@haproxy:5433/ecommerce
      - PGLOAD_SCALE=8
      - PGLOAD_CLIENTS=48
      - PGLOAD_SEED=508516811

volumes:
  prom-data:

networks:
  pg-network:
    # Make sure that the network is created externally. This should be done
    # after running compose file for specific cluster setup.
    name: pg-network
    external: true
