services:
  pg0:
    image: docker.io/bitnami/postgresql-repmgr:17.4.0
    ports:
      - "5000:5432"
    networks:
        - pg-network
    volumes:
      - pg0-data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_CLUSTER_APP_NAME=pg0
      - REPMGR_PRIMARY_HOST=pg0
      - REPMGR_PARTNER_NODES=pg2,pg1,pg0
      - REPMGR_NODE_NAME=pg0
      - REPMGR_NODE_NETWORK_NAME=pg0
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgr

  pg1:
    image: docker.io/bitnami/postgresql-repmgr:17.4.0
    ports:
      - "5001:5432"
    networks:
      - pg-network
    volumes:
      - pg1-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_CLUSTER_APP_NAME=pg1
      - REPMGR_PRIMARY_HOST=pg0
      - REPMGR_PARTNER_NODES=pg0,pg2,pg1
      - REPMGR_NODE_NAME=pg1
      - REPMGR_NODE_NETWORK_NAME=pg1
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgr

  pg2:
    image: docker.io/bitnami/postgresql-repmgr:17.4.0
    ports:
      - "5002:5432"
    networks:
      - pg-network
    volumes:
      - pg2-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_CLUSTER_APP_NAME=pg2
      - REPMGR_PRIMARY_HOST=pg0
      - REPMGR_PARTNER_NODES=pg0,pg1,pg2
      - REPMGR_NODE_NAME=pg2
      - REPMGR_NODE_NETWORK_NAME=pg2
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgr

  pgpool:
    image: docker.io/bitnami/pgpool:4
    ports:
      - "5432:5432"
    networks:
      - pg-network
    environment:
      - PGPOOL_BACKEND_NODES=0:pg0:5432,1:pg1:5432,2:pg2:5432
      - PGPOOL_BACKEND_APPLICATION_NAMES=pg0,pg1,pg2
      - PGPOOL_SR_CHECK_USER=repmgr
      - PGPOOL_SR_CHECK_PASSWORD=repmgr
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=pgpool
      - PGPOOL_ADMIN_PASSWORD=pgpool
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=dba
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=sql
      - PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
      - PGPOOL_AUTO_FAILBACK=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg0-data:
  pg1-data:
  pg2-data:

networks:
  pg-network:
    driver: bridge