services:
  etcd:
    image: docker.io/bitnami/etcd:3.5.21
    networks:
      - pg-network
    volumes:
        - etcd-data:/etcd-data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=pgcluster
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  pg-0:
    image: postgresql-patroni:17.4
    build:
        context: .
        args:
          - PG_VERSION=17.4
    networks:
      - pg-network
    volumes:
      - pg-0-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - PG_PATRONI_NAME=pg-0
      - PG_PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PG_PATRONI_RESTAPI_CONNECT_ADDRESS=pg-0:8008
      - PG_PATRONI_ETCD3_HOST=etcd:2379
      - PG_PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PG_PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg-0:5432

  pg-1:
    image: postgresql-patroni:17.4
    networks:
      - pg-network
    volumes:
      - pg-1-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - PG_PATRONI_NAME=pg-1
      - PG_PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PG_PATRONI_RESTAPI_CONNECT_ADDRESS=pg-1:8008
      - PG_PATRONI_ETCD3_HOST=etcd:2379
      - PG_PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PG_PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg-1:5432

  pg-2:
    image: postgresql-patroni:17.4
    networks:
      - pg-network
    volumes:
      - pg-2-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - PG_PATRONI_NAME=pg-2
      - PG_PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PG_PATRONI_RESTAPI_CONNECT_ADDRESS=pg-2:8008
      - PG_PATRONI_ETCD3_HOST=etcd:2379
      - PG_PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PG_PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg-2:5432

  pg-3:
    image: postgresql-patroni:17.4
    networks:
      - pg-network
    volumes:
      - pg-3-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=dba
      - POSTGRESQL_PASSWORD=sql
      - POSTGRESQL_DATABASE=ecommerce
      - PG_PATRONI_NAME=pg-3
      - PG_PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PG_PATRONI_RESTAPI_CONNECT_ADDRESS=pg-3:8008
      - PG_PATRONI_ETCD3_HOST=etcd:2379
      - PG_PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PG_PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg-3:5432

  haproxy:
    image: docker.io/bitnami/haproxy:3.1.7
    ports:
        - "5432:5000"
        - "5433:5001"
        - "7000:7000"
    networks:
      - pg-network
    volumes:
      - ./haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg

volumes:
  etcd-data:
  pg-0-data:
  pg-1-data:
  pg-2-data:
  pg-3-data:

networks:
  pg-network:
    driver: bridge
