{
 "title": "pgbench-ha-sharding",
 "tags": [
  "pgbench",
  "postgresql",
  "cluster",
  "sharding"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Query Type",
    "query": "label_values(pgload_query_total, type)"
   },
   {
    "name": "node",
    "label": "Node IP",
    "query": "label_values(pgload_query_total, node)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgload_query_latency_seconds_sum[$__range])) / sum(rate(pgload_query_latency_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgload_query_total or vector(0)) - sum(pgload_query_error_total or vector(0))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(increase(pgload_query_error_total[$__range])) or vector(0)",
     "legendFormat": "Errored"
    }
   ]
  },
  {
   "title": "Queries / Seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "QPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgload_query_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average latency per query type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(pgload_query_latency_seconds_sum[$__range])) / sum by (type) (rate(pgload_query_latency_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries / Seconds per query type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "QPS" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(pgload_query_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}